[project]
name = "qzemoji"
version = "6.1.1"
description = "Translate Qzone emoji link to text."
authors = [{ name = "aioqzone" }]
maintainers = [
    { name = "JamzumSum", email = "22952836+JamzumSum@users.noreply.github.com" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.10",
    "aiofiles>=24.1",
    "SQLAlchemy[asyncio,aiosqlite]>=2.0",
    "PyYAML>=6.0",
]

[project.urls]
Homepage = "https://github.com/aioqzone/QzEmoji"
Repository = "https://github.com/aioqzone/QzEmoji"

[dependency-groups]
dev = ["black", "ruff"]
test = ["pytest>=8.2.1", "pytest-asyncio~=1.2.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = 'src'
log_cli = true
log_cli_level = 'WARNING'

[tool.ruff]
line-length = 99
