[project]
name = "qzemoji"
version = "7.0.1"
description = "Translate Qzone emoji link to text."
authors = [{ name = "aioqzone" }]
maintainers = [
    { name = "JamzumSum", email = "22952836+JamzumSum@users.noreply.github.com" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.13.3",
    "aiofiles>=24.1",
    "SQLAlchemy[asyncio,aiosqlite]>=2.0.44",
    "greenlet>=3.2.3",
    "PyYAML>=6.0",
]

[project.urls]
Homepage = "https://github.com/aioqzone/QzEmoji"
Repository = "https://github.com/aioqzone/QzEmoji"

[dependency-groups]
dev = ["ruff"]
test = ["pytest>=9.0.3", "pytest-asyncio~=1.1"]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = 'src'
log_cli = true
log_cli_level = 'WARNING'

[tool.ruff]
line-length = 99
